In [1]:
import numpy as np

In [34]:
A = np.array([[1, 4, 5, 12], 
              [-5, 8, 9, 0],
              [-6, 7, 11, 19]])

In [35]:
type(A)

numpy.ndarray

In [36]:
A[1].shape

(4,)

In [37]:
np.argsort(A[1])

array([0, 3, 1, 2], dtype=int64)

In [39]:
A[1][np.argsort(A[1])]

array([-5,  0,  8,  9])

In [46]:
A[:, :] - [1,1,1,1]

array([[ 0,  3,  4, 11],
       [-6,  7,  8, -1],
       [-7,  6, 10, 18]])